In [1]:
import numpy as np

nx, nl = 5, 8

x = np.random.rand(1, nx)
W = np.random.rand(nl, nx)
b = np.random.rand(nl, 1)

In [2]:
x

array([[0.17787518, 0.86299149, 0.07910303, 0.69165295, 0.07596235]])

In [3]:
W

array([[0.4627152 , 0.96383092, 0.07372672, 0.33741536, 0.07921071],
       [0.13590913, 0.44754247, 0.50621953, 0.44108642, 0.9773853 ],
       [0.94429355, 0.54739971, 0.62222561, 0.67260941, 0.71097782],
       [0.22054781, 0.4784106 , 0.36301165, 0.2784047 , 0.53131027],
       [0.42994266, 0.0198255 , 0.16704641, 0.62725969, 0.42009833],
       [0.15749433, 0.40833651, 0.48054775, 0.18908155, 0.03649211],
       [0.79680566, 0.96267646, 0.18624779, 0.59326917, 0.60142159],
       [0.23277045, 0.03801724, 0.32300443, 0.3181788 , 0.48317954]])

In [4]:
b

array([[0.8898765 ],
       [0.71547119],
       [0.47856412],
       [0.06006578],
       [0.6159061 ],
       [0.65971039],
       [0.35883692],
       [0.62598387]])

In [5]:
z = np.matmul(W, x.T) + b
z

array([[2.0491833 ],
       [1.54523811],
       [1.68737156],
       [0.77379436],
       [1.18846301],
       [1.21167928],
       [1.802105  ],
       [0.9825199 ]])

In [6]:
x.shape, W.shape, b.shape, z.shape

((1, 5), (8, 5), (8, 1), (8, 1))

In [7]:
x

array([[0.17787518, 0.86299149, 0.07910303, 0.69165295, 0.07596235]])

In [8]:
W[i][j]

NameError: name 'i' is not defined

In [30]:
x[0][j]

0.19104794746241538

In [36]:
output = []
for i in range(nl):
    z = 0
    for j in range(nx):
        z += W[i][j] * x[0][j]
    z += b[i][0]
	#a = sigma(z)
    output.append(z)
output

[1.3359164276804185,
 1.1908660978508552,
 1.740008757090468,
 1.2645889350506683,
 1.5316883864471422,
 0.8802054451461725,
 2.0760973511924496,
 1.6153299875643692]

In [49]:
import numpy as np

nd, nx, nl = 10, 5, 3
n1, n2, n3 = 8, 12, 2

# input and parameters initializations
x = np.random.rand(nd, nx)
W1 = np.random.rand(n1, nx)
b1 = np.random.rand(n1, 1)
W2 = np.random.rand(n2, n1)
b2 = np.random.rand(n2, 1)
W3 = np.random.rand(n3, n2)
b3 = np.random.rand(n3, 1)

# layer wise computations
a0 = x.T
a1 = np.matmul(W1, a0) + b1
print(f"Shape of a1: {a1.shape}")

a2 = np.matmul(W2, a1) + b2
print(f"Shape of a2: {a2.shape}")

a3 = np.matmul(W3, a2) + b3
print(f"Shape of a3: {a3.shape}")

print(f"Outputs of the network:") 
print(a3)

Shape of a1: (8, 10)
Shape of a2: (12, 10)
Shape of a3: (2, 10)
Outputs of the network:
[[42.32577663 38.25657388 38.793039   51.37741944 50.25508806 43.39397785
  38.70736228 39.76630318 42.07832858 49.0518998 ]
 [43.38407575 39.19592829 39.95172035 52.52103437 51.25087396 44.46149484
  39.68241389 41.03009743 43.07179737 50.08075683]]


In [45]:
import torch 

import torch.nn as nn

l1 = nn.Linear(nx, n1)
l2 = nn.Linear(n1, n2)
l3 = nn.Linear(n2, n3)

tensorX = torch.from_numpy(x)

In [46]:
l1.bias.data.shape

torch.Size([8])

In [47]:
# initialize same weights
l1.weight.data = torch.from_numpy(W1)
l1.bias.data = torch.from_numpy(b1.squeeze())

l2.weight.data = torch.from_numpy(W2)
l2.bias.data = torch.from_numpy(b2.squeeze())

l3.weight.data = torch.from_numpy(W3)
l3.bias.data = torch.from_numpy(b3.squeeze())

a1 = l1(tensorX)
print(f"Shape of a1: {a1.shape}")

Shape of a1: torch.Size([10, 8])


In [48]:
a2 = l2(a1)
print(f"Shape of a1: {a2.shape}")

a3 = l3(a2)
print(f"Shape of a3: {a3.shape}")

print(a3)

Shape of a1: torch.Size([10, 12])
Shape of a3: torch.Size([10, 2])
tensor([[47.5938, 47.6577],
        [41.8636, 41.9331],
        [49.3240, 49.2304],
        [56.3790, 56.3068],
        [60.5699, 60.3729],
        [67.4708, 67.3726],
        [46.0356, 45.7477],
        [49.1432, 48.5770],
        [39.6412, 39.7168],
        [56.5418, 56.5354]], dtype=torch.float64, grad_fn=<AddmmBackward0>)


In [51]:
layer1 = nn.Linear(nx, 8)
layer2 = nn.Linear(8, 1)

net = nn.Sequential(layer1, layer2)

In [56]:
net(tensorX.float())

tensor([[0.1316],
        [0.1746],
        [0.4524],
        [0.1258],
        [0.1228],
        [0.0305],
        [0.0638],
        [0.4189],
        [0.1141],
        [0.2077]], grad_fn=<AddmmBackward0>)

In [58]:
layer1.parameters.

<bound method Module.parameters of Linear(in_features=5, out_features=8, bias=True)>

In [2]:
import torch
import torch.nn as nn

nd, nx, ny = 15, 5, 1

# number of units per layer
n1, n2 = 8, ny

# generating random inputs
X = torch.rand(nd, nx)

# create the model
layer1 = nn.Linear(nx, 8)
layer2 = nn.Linear(8, ny)

net = nn.Sequential(layer1, layer2)

# feed the inputs to the network
y = net(X)

print(y)

tensor([[-0.0874],
        [ 0.0077],
        [ 0.0467],
        [-0.0368],
        [-0.0522],
        [-0.0352],
        [-0.0660],
        [-0.1449],
        [-0.0448],
        [-0.0585],
        [-0.0644],
        [ 0.0251],
        [-0.0828],
        [ 0.0262],
        [-0.0222]], grad_fn=<AddmmBackward0>)


In [6]:
X.size(), y.size()

(torch.Size([15, 5]), torch.Size([15, 1]))

In [7]:
a1 = layer1(X)
a1.shape

torch.Size([15, 8])

In [8]:
a2 = layer2(a1)
a2.shape

torch.Size([15, 1])

In [12]:
print(f"Shape of layer 1 weight matrix: {layer1.weight.size()}")
print(f"Shape of layer 1 bias vector: {layer1.bias.size()}")
print(f"Shape of layer 2 weight matrix: {layer2.weight.size()}")
print(f"Shape of layer 2 bias vector: {layer2.bias.size()}")

Shape of layer 1 weight matrix: torch.Size([8, 5])
Shape of layer 1 bias vector: torch.Size([8])
Shape of layer 2 weight matrix: torch.Size([1, 8])
Shape of layer 2 bias vector: torch.Size([1])


In [21]:
# output using pytorch layer
a1 = layer1(X)

# output using equation
# get the weights and biases in layer 1
w1 = layer1.weight.data
b1 = layer1.bias.data
a1_eq = torch.matmul(X, w1.T) + b1

print(f"Layer 1 outputs using pytorch and equation are same: {torch.equal(a1,a1_eq)}")

# output using pytorch layer
y = layer2(a1)

# output using equation
# get the weights and biases in layer 2
w2 = layer2.weight.data
b2 = layer2.bias.data
a2_eq = torch.matmul(a1, w2.T) + b2

print(f"Layer 2 outputs using pytorch and equation are same: {torch.equal(a2,a2_eq)}")

Layer 1 outputs using pytorch and equation are same: True
Layer 2 outputs using pytorch and equation are same: True


In [18]:
a1.size()

torch.Size([15, 8])

In [15]:
a1_eq

tensor([[ 0.2938,  0.2804,  0.1864, -1.0719, -0.3100,  0.4171, -0.6768, -0.4951],
        [-0.0168,  0.5160,  0.1586, -0.8783, -0.3247,  0.4362, -0.6849, -0.3100],
        [ 0.0728,  0.4925,  0.0500, -1.5611, -0.2295,  1.0128, -1.2110, -0.7668],
        [ 0.0559,  0.4410,  0.1214, -1.0129, -0.0785,  0.4003, -0.6379, -0.6821],
        [-0.0299,  0.5090,  0.1316, -1.1781, -0.1768,  0.6810, -0.8994, -0.6171],
        [ 0.0743,  0.3765,  0.2159, -1.2684,  0.0043,  0.6557, -0.8886, -0.9264],
        [ 0.2716,  0.2559,  0.1998, -0.9441, -0.3341,  0.2832, -0.5235, -0.3417],
        [-0.1167,  0.6045,  0.0032, -1.2044, -0.1450,  0.6960, -0.8780, -0.6016],
        [ 0.1181,  0.4572,  0.0832, -1.4706, -0.2388,  0.9093, -1.1287, -0.7437],
        [ 0.2152,  0.2754,  0.2461, -0.9803, -0.1120,  0.3083, -0.5719, -0.6760],
        [ 0.1061,  0.3696,  0.1640, -1.0817, -0.0322,  0.4229, -0.6564, -0.7731],
        [ 0.0941,  0.4238,  0.1482, -0.9616, -0.3230,  0.4241, -0.6601, -0.3478],
        [ 0.2915

In [4]:
X.size()[0]

15

In [23]:
y.detach()

tensor([[-0.0874],
        [ 0.0077],
        [ 0.0467],
        [-0.0368],
        [-0.0522],
        [-0.0352],
        [-0.0660],
        [-0.1449],
        [-0.0448],
        [-0.0585],
        [-0.0644],
        [ 0.0251],
        [-0.0828],
        [ 0.0262],
        [-0.0222]])

In [26]:
loop_y = torch.zeros_like(y)

for i in range(X.size()[0]):
    loop_y[i] = net(X[i])

print(loop_y)

Outputs using pytorch and loop are same: False


In [27]:
loop_y.detach()

tensor([[-0.0874],
        [ 0.0077],
        [ 0.0467],
        [-0.0368],
        [-0.0522],
        [-0.0352],
        [-0.0660],
        [-0.1449],
        [-0.0448],
        [-0.0585],
        [-0.0644],
        [ 0.0251],
        [-0.0828],
        [ 0.0262],
        [-0.0222]])